apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-poc
---
apiVersion: v1
kind: Secret
metadata:
   name: mysql-bd-secret-config
   namespace: wordpress-poc
type: Opaque
data:
   password: -------------
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-poc-mysql-service
  namespace: wordpress-poc
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-poc-bd-data-pv
  namespace: wordpress-poc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /volumenes/wordpress-poc/bd/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubwebnodo1
          - kubwebnodo2
          - kubwebnodo3
---   
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bd-data-pvc
  namespace: wordpress-poc
  labels:
    app: wordpress  
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: wordpress-poc-bd-data-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-poc-bd
  namespace: wordpress-poc  
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql        
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-bd-secret-config
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-bd-secret-config
                  key: password                      
          volumeMounts:             
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage                  
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: bd-data-pvc
